Repository UnnecessaryRain/ironway-core, pull requests merged in 2018-04, with the labels that each got.

#3 Basic concurrent game model
  cmd/gamecommand/gamecommand.go
  cmd/serveCommand/serveCommand.go
  ironway.go
  pkg/game/command.go
  pkg/game/commands/debug.go
  pkg/game/game.go
  pkg/network/client/client.go
  pkg/network/protocol/constants.go
  pkg/network/protocol/message.go
  pkg/network/protocol/packet.go
  pkg/network/server/server.go
  pkg/network/server/websocket.go
Labels: feature

#5 Add command interpretation
  cmd/gamecommand/gamecommand.go
  pkg/game/commands/chat.go
  pkg/game/commands/debug.go
  pkg/game/commands/notfound.go
  pkg/interpreter/interpreter.go
Labels: feature

#7 Added reply method to command
  cmd/gamecommand/gamecommand.go
  cmd/serveCommand/serveCommand.go
  pkg/game/command.go
  pkg/game/commands/chat.go
  pkg/game/commands/debug.go
  pkg/game/commands/notfound.go
  pkg/game/game.go
  pkg/network/client/client.go
  pkg/network/server/server.go
Labels: feature

#8 Refactor message protocol
  cmd/gamecmd/gamecmd.go
  cmd/servecmd/servecmd.go
  ironway.go
  pkg/game/commands/chat.go
  pkg/mud/chat/chat.go
  pkg/mud/commands/chat.go
  pkg/mud/commands/debug.go
  pkg/mud/commands/notfound.go
  pkg/mud/game/command.go
  pkg/mud/game/game.go
  pkg/mud/interpreter/interpreter.go
  pkg/network/client/client.go
  pkg/network/protocol/constants.go
  pkg/network/protocol/message.go
  pkg/network/protocol/packet.go
  pkg/network/protocol/sender.go
  pkg/network/server/server.go
Labels: code base, feature

#9 basic online auth
  pkg/mud/commands/chat.go
  pkg/mud/commands/notfound.go
  pkg/mud/game/game.go
  pkg/mud/interpreter/interpreter.go
  pkg/network/client/client.go
  pkg/network/protocol/constants.go
  pkg/network/server/server.go
  pkg/network/server/websocket.go
Labels: code base
